#### PYTHON 26-4-24

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### linear model for classification

#### In a two dimentional binary classification problem

In [43]:
from sklearn.datasets import load_breast_cancer

In [46]:
df = load_breast_cancer()

In [4]:
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [26]:
X = pd.DataFrame(df.data,columns = df.feature_names)

In [27]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [28]:
X.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [29]:
X.size

17070

In [47]:
y = pd.DataFrame(df.target,columns = ['Cancer'])

In [48]:
df.target_names

array(['malignant', 'benign'], dtype='<U9')

In [31]:
df.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [10]:
y.head()

Cancer
0       0
1       0
2       0
3       0
4       0

In [11]:
y['Cancer'].unique()

array([0, 1])

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression

In [103]:
Log_Model = LogisticRegression(C=0.2)

In [104]:
Log_Model.fit(X_train,y_train)

C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.2)

In [105]:
y_pred = Log_Model.predict(X_test)
y_val = Log_Model.predict(X_train)

In [86]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [87]:
train_accuracy = accuracy_score(y_val,y_train)
test_accuracy = accuracy_score(y_pred,y_test)

In [106]:
print(train_accuracy,test_accuracy)

0.9396984924623115 0.9707602339181286


In [89]:
print(train_accuracy,test_accuracy) # this is overfitting, the test should not be more than train

0.9396984924623115 0.9707602339181286


In [107]:
confusion_matrix(y_pred,y_test)

array([[ 60,   1],
       [  3, 107]], dtype=int64)

In [108]:
from sklearn.svm import LinearSVC

In [112]:
SVC_Model=LinearSVC()

In [113]:
SVC_Model.fit(X_train,y_train)

C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [115]:
y_pred = SVC_Model.predict(X_test)

In [116]:
y_val = SVC_Model.predict(X_train)

In [118]:
Test_report = classification_report(y_pred,y_test)
print(Test_report)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94        56
           1       1.00      0.94      0.97       115

    accuracy                           0.96       171
   macro avg       0.94      0.97      0.95       171
weighted avg       0.96      0.96      0.96       171



In [97]:
Test_report = classification_report(y_val,y_train)
print(Test_report)

              precision    recall  f1-score   support

           0       0.82      0.96      0.88       127
           1       0.98      0.90      0.94       271

    accuracy                           0.92       398
   macro avg       0.90      0.93      0.91       398
weighted avg       0.93      0.92      0.92       398



In [119]:
confusion_matrix(y_pred,y_test)

array([[ 56,   0],
       [  7, 108]], dtype=int64)

In [122]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5)

In [123]:
SVC_Model.fit(X_train,y_train)

C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [125]:
y_pred = SVC_Model.predict(X_test)

In [127]:
accuracy_1 = accuracy_score(y_pred,y_test)
accuracy_1

0.8736842105263158

In [128]:
SVC_Model.fit(X_test,y_test)

C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [129]:
y_pred2 = SVC_Model.predict(X_train)

In [130]:
accuracy_2 = accuracy_score(y_pred2,y_train)
accuracy_2

0.6549295774647887

In [132]:
from sklearn.model_selection import cross_val_score

In [134]:
Result = cross_val_score(SVC_Model,X,y,cv = 5)

C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
C:\Users\GABRIEL SIMDIMA\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GABRIEL SIMD

In [136]:
print(Result)

[0.92105263 0.9122807  0.92105263 0.93859649 0.94690265]
